### ISSUE TITLE
0 comments in code, documentation doesn't explain how to set anything up. Nothing works.

### ISSUE THREAD

**Issue by JustTryingToGetSomeWorkDone** [luisllamasbinaburo/NppArduino#3]
In addition to a lack of documentation (ok, there's a tiny amount, but only enough to frustrate people), there's not a single useful comment in the entire codebase. How do I point to my arduino-cli installation? (assuming that's why it doesn't work) How do I do anything other than add it to my plugin directory? I don't have the time or motivation to learn how to make Notepad++ plugins right now, so fixing it is pretty much off the table.

Like the only other reported issue, I cannot get any of my boards to show up in the plugin. My COM port populates properly, but the board that I have connected to that COM port and that shows up in arduino-cli never appears in the board list. Nothing does. Everything but the port field is empty. Refresh does nothing, Compile does nothing. Upload does nothing. I can toggle the serial monitor between connect and disconnect, but it does nothing. Even when I know my board is sending data over serial, it doesn't show anything.

At the moment this is a dead and non-working project. That's too bad. I think a lot of people could find it useful as they attempt to get away from the slow garbage fire that is Arduino IDE 2.X.

I hope you can at least find the time to point us in the right direction. Otherwise, maybe just archive it and make the repository read only so people will know not to expect anything before wasting their time.

**Comment by luisllamasbinaburo** [comment]
Hello. I'm not sure if you're familiar with how Open Source projects work. Seeing that you have a total of ZERO shared repositories, I assume you're not.

Open Source is about collaboration. If you think documentation or code can be improved, any contribution is welcome.
You said that "I don't have the time or motivation to learn how to make Notepad++ plugins right now, so fixing it is pretty much off the table"... well, is really lame assume that other people are going to do this work by you.

Also, phrases like this "enough to frustrate people", or this "people will know not to expect anything before wasting their time", are generally out of context and not well-received.

If you want to contribute constructively, you will find people happy to collaborate.
Otherwise, the "right direction" I'll point you to is outside my Github
